// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.p0rn.entities;

privileged aspect Riik_Roo_JavaBean {
    
    public int Riik.getRiik_ID() {
        return this.riik_ID;
    }
    
    public void Riik.setRiik_ID(int riik_ID) {
        this.riik_ID = riik_ID;
    }
    
}
